package dev.vfyjxf.taffy.tree;

import dev.vfyjxf.taffy.geometry.FloatLine;
import dev.vfyjxf.taffy.geometry.FloatRect;
import dev.vfyjxf.taffy.geometry.TaffyLine;
import dev.vfyjxf.taffy.style.GridPlacement;
import dev.vfyjxf.taffy.style.TaffyDirection;
import dev.vfyjxf.taffy.style.TrackSizingFunction;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;

/** Detailed track and item information produced by a grid layout. */
public class DetailedGridInfo {
    private final DetailedGridTracksInfo rows;
    private final DetailedGridTracksInfo columns;
    private final List<DetailedGridItemInfo> items;
    private final String gridTemplateRows;
    private final String gridTemplateColumns;

    public DetailedGridInfo(
        DetailedGridTracksInfo rows,
        DetailedGridTracksInfo columns,
        List<DetailedGridItemInfo> items,
        String gridTemplateRows,
        String gridTemplateColumns) {
        this.rows = rows;
        this.columns = columns;
        this.items = Collections.unmodifiableList(new ArrayList<>(items == null ? Collections.emptyList() : items));
        this.gridTemplateRows = gridTemplateRows == null ? "" : gridTemplateRows;
        this.gridTemplateColumns = gridTemplateColumns == null ? "" : gridTemplateColumns;
    }

    public DetailedGridTracksInfo rows() {
        return rows;
    }

    public DetailedGridTracksInfo columns() {
        return columns;
    }

    public List<DetailedGridItemInfo> items() {
        return items;
    }

    /** Return the used row track list in resolved CSS-like form. */
    public String gridTemplateRows() {
        return gridTemplateRows;
    }

    /** Return the used column track list in resolved CSS-like form. */
    public String gridTemplateColumns() {
        return gridTemplateColumns;
    }

    /** Return the physical area occupied by an item, or null for an invalid index. */
    public FloatRect itemGridArea(int itemIndex) {
        if (itemIndex < 0 || itemIndex >= items.size()) return null;
        DetailedGridItemInfo item = items.get(itemIndex);
        FloatLine columnStart = columns.positionForTrackLine(item.columnStart());
        FloatLine columnEnd = columns.positionForTrackLine(item.columnEnd() - 1);
        FloatLine rowStart = rows.positionForTrackLine(item.rowStart());
        FloatLine rowEnd = rows.positionForTrackLine(item.rowEnd() - 1);
        if (columnStart == null || columnEnd == null || rowStart == null || rowEnd == null) return null;
        return FloatRect.ltrb(
            Math.min(columnStart.start, columnEnd.start),
            Math.min(rowStart.start, rowEnd.start),
            Math.max(columnStart.end, columnEnd.end),
            Math.max(rowStart.end, rowEnd.end));
    }

    /**
     * Resolve an absolutely positioned grid area from numeric line placements.
     * Named and span placements remain auto when they cannot be resolved without style data.
     */
    public FloatRect resolveAbsoluteGridArea(
        TaffyLine<GridPlacement> gridRow,
        TaffyLine<GridPlacement> gridColumn,
        TaffyDirection direction,
        FloatRect paddingBox) {
        if (paddingBox == null) return null;
        Integer rowStart = rows.resolveLine(gridRow == null ? null : gridRow.start, true);
        Integer rowEnd = rows.resolveLine(gridRow == null ? null : gridRow.end, false);
        Integer columnStart = columns.resolveLine(gridColumn == null ? null : gridColumn.start, true);
        Integer columnEnd = columns.resolveLine(gridColumn == null ? null : gridColumn.end, false);
        FloatLine row = resolveLinePair(rows, rowStart, rowEnd, paddingBox.top, paddingBox.bottom, false);
        FloatLine column = resolveLinePair(columns, columnStart, columnEnd, paddingBox.left, paddingBox.right,
            direction != null && direction.isRtl());
        return FloatRect.ltrb(column.start, row.start, column.end, row.end);
    }

    private static FloatLine resolveLinePair(
        DetailedGridTracksInfo tracks,
        Integer start,
        Integer end,
        float fallbackStart,
        float fallbackEnd,
        boolean reversed) {
        float startPosition = tracks.linePosition(start, fallbackStart, fallbackEnd, reversed, true);
        float endPosition = tracks.linePosition(end, fallbackStart, fallbackEnd, reversed, false);
        return new FloatLine(Math.min(startPosition, endPosition), Math.max(startPosition, endPosition));
    }

    /** Build detail metadata from the values generated by GridComputer. */
    public static DetailedGridInfo from(
        TrackCounts rowCounts,
        TrackCounts columnCounts,
        List<Float> rowSizes,
        List<Float> columnSizes,
        List<Float> rowOffsets,
        List<Float> columnOffsets,
        List<DetailedGridItemInfo> items,
        List<TrackSizingFunction> rowTemplate,
        List<TrackSizingFunction> columnTemplate) {
        DetailedGridTracksInfo rows = DetailedGridTracksInfo.from(rowCounts, rowSizes, rowOffsets);
        DetailedGridTracksInfo columns = DetailedGridTracksInfo.from(columnCounts, columnSizes, columnOffsets);
        return new DetailedGridInfo(rows, columns, items, resolvedTemplate(rowSizes), resolvedTemplate(columnSizes));
    }

    private static String resolvedTemplate(List<Float> sizes) {
        StringBuilder builder = new StringBuilder();
        for (Float size : sizes) {
            if (builder.length() > 0) builder.append(' ');
            builder.append(String.format(Locale.ROOT, "%.4f", size)).append("px");
        }
        return builder.toString();
    }

    @Override
    public String toString() {
        return "DetailedGridInfo{rows=" + rows + ", columns=" + columns + ", items=" + items.size() + "}";
    }
}
