package dev.vfyjxf.taffy.tree;

import dev.vfyjxf.taffy.geometry.FloatPoint;
import dev.vfyjxf.taffy.geometry.FloatRect;
import dev.vfyjxf.taffy.geometry.FloatSize;

import java.util.List;

/**
 * A struct containing the result of laying out a single node.
 *
 * @param size The size of the node
 * @param contentSize The size of the content within the node
 * @param firstBaselines The first baseline of the node in each dimension
 * @param topMargin Top margin that can collapse with another margin
 * @param bottomMargin Bottom margin that can collapse with another margin
 * @param marginsCanCollapseThrough Whether margins can collapse through this node
 * @param scrollableOverflowRect The overflow rectangle in the node's coordinate space
 * @param baselines The first and last baselines generated by this node
 */
public record LayoutOutput(
    FloatSize size,
    FloatSize contentSize,
    FloatPoint firstBaselines,
    CollapsibleMarginSet topMargin,
    CollapsibleMarginSet bottomMargin,
    boolean marginsCanCollapseThrough,
    FloatRect scrollableOverflowRect,
    Baselines baselines,
    List<OofCandidate> oofCandidates,
    OofPositioningArea oofPositioningArea
) {

    public LayoutOutput {
        if (scrollableOverflowRect == null) {
            scrollableOverflowRect = overflowFromContent(contentSize);
        }
        if (baselines == null) {
            baselines = Baselines.NONE;
        }
        oofCandidates = oofCandidates == null ? List.of() : List.copyOf(oofCandidates);
    }

    public LayoutOutput(FloatSize size, FloatSize contentSize, FloatPoint firstBaselines,
                        CollapsibleMarginSet topMargin, CollapsibleMarginSet bottomMargin,
                        boolean marginsCanCollapseThrough, FloatRect scrollableOverflowRect, Baselines baselines) {
        this(size, contentSize, firstBaselines, topMargin, bottomMargin, marginsCanCollapseThrough,
            scrollableOverflowRect, baselines, List.of(), null);
    }

    /**
     * Compatibility constructor for callers using the pre-Rust-0.14 output shape.
     */
    public LayoutOutput(
        FloatSize size,
        FloatSize contentSize,
        FloatPoint firstBaselines,
        CollapsibleMarginSet topMargin,
        CollapsibleMarginSet bottomMargin,
        boolean marginsCanCollapseThrough
    ) {
        this(
            size,
            contentSize,
            firstBaselines,
            topMargin,
            bottomMargin,
            marginsCanCollapseThrough,
            overflowFromContent(contentSize),
            Baselines.fromLegacy(firstBaselines == null ? Float.NaN : firstBaselines.y)
        );
    }

    /**
     * An all-zero LayoutOutput for hidden nodes.
     */
    public static final LayoutOutput HIDDEN = new LayoutOutput(
        FloatSize.zero(),
        FloatSize.zero(),
        new FloatPoint(Float.NaN, Float.NaN),
        CollapsibleMarginSet.ZERO,
        CollapsibleMarginSet.ZERO,
        false,
        FloatRect.zero(),
        Baselines.NONE
    );

    /**
     * Static factory method for hidden layout output.
     */
    public static LayoutOutput hidden() {
        return HIDDEN;
    }

    /**
     * A blank layout output.
     */
    public static final LayoutOutput DEFAULT = HIDDEN;

    /**
     * Create a LayoutOutput from the size and baselines.
     */
    public static LayoutOutput fromSizesAndBaselines(
        FloatSize size,
        FloatSize contentSize,
        FloatPoint firstBaselines
    ) {
        return new LayoutOutput(
            size,
            contentSize,
            firstBaselines,
            CollapsibleMarginSet.ZERO,
            CollapsibleMarginSet.ZERO,
            false
        );
    }

    /** Create an output using the Rust-style baseline pair. */
    public static LayoutOutput fromSizesAndBaselines(
        FloatSize size,
        FloatSize contentSize,
        Baselines baselines
    ) {
        Baselines safeBaselines = baselines == null ? Baselines.NONE : baselines;
        return new LayoutOutput(
            size,
            contentSize,
            new FloatPoint(Float.NaN, safeBaselines.first()),
            CollapsibleMarginSet.ZERO,
            CollapsibleMarginSet.ZERO,
            false,
            overflowFromContent(contentSize),
            safeBaselines
        );
    }

    /** Create an output with explicit overflow and baseline metadata. */
    public static LayoutOutput fromSizesAndOverflow(
        FloatSize size,
        FloatSize contentSize,
        FloatRect scrollableOverflowRect,
        Baselines baselines
    ) {
        Baselines safeBaselines = baselines == null ? Baselines.NONE : baselines;
        return new LayoutOutput(
            size,
            contentSize,
            new FloatPoint(Float.NaN, safeBaselines.first()),
            CollapsibleMarginSet.ZERO,
            CollapsibleMarginSet.ZERO,
            false,
            scrollableOverflowRect == null ? overflowFromContent(contentSize) : scrollableOverflowRect,
            safeBaselines
        );
    }

    /** Rust-compatible constructor using size, overflow rectangle, and baselines. */
    public static LayoutOutput fromSizesAndBaselines(
        FloatSize size,
        FloatRect scrollableOverflowRect,
        Baselines baselines
    ) {
        Baselines safeBaselines = baselines == null ? Baselines.NONE : baselines;
        return new LayoutOutput(
            size,
            size,
            new FloatPoint(Float.NaN, safeBaselines.first()),
            CollapsibleMarginSet.ZERO,
            CollapsibleMarginSet.ZERO,
            false,
            scrollableOverflowRect == null ? FloatRect.zero() : scrollableOverflowRect,
            safeBaselines
        );
    }

    /** Rust-compatible constructor using size and scrollable overflow rectangle. */
    public static LayoutOutput fromSizesWithOverflow(FloatSize size, FloatRect scrollableOverflowRect) {
        return fromSizesAndBaselines(size, scrollableOverflowRect, Baselines.NONE);
    }

    /**
     * Construct a LayoutOutput from container and content sizes.
     */
    public static LayoutOutput fromSizes(FloatSize size, FloatSize contentSize) {
        return fromSizesAndBaselines(size, contentSize, new FloatPoint(Float.NaN, Float.NaN));
    }

    /**
     * Construct a LayoutOutput from the container size.
     */
    public static LayoutOutput fromOuterSize(FloatSize size) {
        return fromSizes(size, FloatSize.zero());
    }

    /** Return this output with pending out-of-flow candidates and their positioning area. */
    public LayoutOutput withOutOfFlow(List<OofCandidate> candidates, OofPositioningArea positioningArea) {
        return new LayoutOutput(
            size,
            contentSize,
            firstBaselines,
            topMargin,
            bottomMargin,
            marginsCanCollapseThrough,
            scrollableOverflowRect,
            baselines,
            candidates,
            positioningArea
        );
    }

    private static FloatRect overflowFromContent(FloatSize contentSize) {
        if (contentSize == null || Float.isNaN(contentSize.width) || Float.isNaN(contentSize.height)) {
            return FloatRect.zero();
        }
        return FloatRect.ltrb(0f, 0f, contentSize.width, contentSize.height);
    }

    @Override
    public String toString() {
        return "LayoutOutput{size=" + size + ", contentSize=" + contentSize
            + ", scrollableOverflowRect=" + scrollableOverflowRect
            + ", baselines=" + baselines + "}";
    }
}
