package dev.vfyjxf.taffy.tree;

import dev.vfyjxf.taffy.geometry.FloatPoint;
import dev.vfyjxf.taffy.geometry.FloatRect;
import dev.vfyjxf.taffy.geometry.FloatSize;

/**
 * The final result of a layout algorithm for a single node.
 *
 * @param order Relative ordering of the node
 * @param location Top-left corner of the node
 * @param size Width and height of the node
 * @param contentSize Width and height of the content inside the node
 * @param scrollbarSize Size of the scrollbars in each dimension
 * @param border Size of the borders of the node
 * @param padding Size of the padding of the node
 * @param margin Size of the margin of the node
 * @param scrollableOverflowRect Scrollable overflow in the node's border-box coordinates
 * @param baselines First and last baselines generated by the node
 */
public record Layout(
    int order,
    FloatPoint location,
    FloatSize size,
    FloatSize contentSize,
    FloatSize scrollbarSize,
    FloatRect border,
    FloatRect padding,
    FloatRect margin,
    FloatRect scrollableOverflowRect,
    Baselines baselines
) {

    public Layout {
        if (scrollableOverflowRect == null) {
            scrollableOverflowRect = contentOverflow(contentSize);
        }
        if (baselines == null) {
            baselines = Baselines.NONE;
        }
    }

    /** Compatibility constructor for the pre-Rust-0.14 layout shape. */
    public Layout(
        int order,
        FloatPoint location,
        FloatSize size,
        FloatSize contentSize,
        FloatSize scrollbarSize,
        FloatRect border,
        FloatRect padding,
        FloatRect margin
    ) {
        this(
            order,
            location,
            size,
            contentSize,
            scrollbarSize,
            border,
            padding,
            margin,
            contentOverflow(contentSize),
            Baselines.NONE
        );
    }

    /**
     * Creates a new zero Layout.
     */
    public Layout() {
        this(0, FloatPoint.zero(), FloatSize.zero(), FloatSize.zero(), FloatSize.zero(), FloatRect.zero(), FloatRect.zero(), FloatRect.zero(), FloatRect.zero(), Baselines.NONE);
    }

    /**
     * Creates a new Layout with the supplied order value.
     */
    public Layout(int order) {
        this(order, FloatPoint.zero(), FloatSize.zero(), FloatSize.zero(), FloatSize.zero(), FloatRect.zero(), FloatRect.zero(), FloatRect.zero(), FloatRect.zero(), Baselines.NONE);
    }

    /**
     * Creates a new Layout with the given order.
     */
    public static Layout withOrder(int order) {
        return new Layout(order);
    }

    /**
     * Copy this layout and its mutable geometry values.
     */
    public Layout copy() {
        return new Layout(
            order,
            location.copy(),
            size.copy(),
            contentSize.copy(),
            scrollbarSize.copy(),
            border.copy(),
            padding.copy(),
            margin.copy(),
            scrollableOverflowRect.copy(),
            baselines
        );
    }

    private static FloatRect contentOverflow(FloatSize contentSize) {
        if (contentSize == null || Float.isNaN(contentSize.width) || Float.isNaN(contentSize.height)) {
            return FloatRect.zero();
        }
        return FloatRect.ltrb(0f, 0f, contentSize.width, contentSize.height);
    }

    /**
     * Get the width of the content box.
     */
    public float contentBoxWidth() {
        return size.width - padding.left - padding.right - border.left - border.right;
    }

    /**
     * Get the height of the content box.
     */
    public float contentBoxHeight() {
        return size.height - padding.top - padding.bottom - border.top - border.bottom;
    }

    /**
     * Get the size of the content box.
     */
    public FloatSize contentBoxSize() {
        return new FloatSize(contentBoxWidth(), contentBoxHeight());
    }

    /**
     * Get the x offset of the content box relative to its parent border box.
     */
    public float contentBoxX() {
        return location.x + border.left + padding.left;
    }

    /**
     * Get the y offset of the content box relative to its parent border box.
     */
    public float contentBoxY() {
        return location.y + border.top + padding.top;
    }

    /**
     * Return the scroll width of the node.
     */
    public float scrollWidth() {
        return Math.max(0, scrollableOverflowRect.right + Math.min(scrollbarSize.width, size.width)
            - size.width + border.left + border.right);
    }

    /**
     * Return the scroll height of the node.
     */
    public float scrollHeight() {
        return Math.max(0, scrollableOverflowRect.bottom + Math.min(scrollbarSize.height, size.height)
            - size.height + border.top + border.bottom);
    }

    @Override
    public String toString() {
        return "Layout{order=" + order + ", location=" + location + ", size=" + size + "}";
    }
}
